name: Build APP

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - assembleFullDebug
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
      - name: Build with Gradle
        run: ./gradlew ${{ matrix.task }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: app/build/outputs/apk/full/debug/app-full-debug.apk
          if-no-files-found: error
          retention-days: 1
